on:
  workflow_dispatch:
    inputs:
      address:
        description: "Resource address to remove from state"
        required: true

jobs:
  state-rm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: terraform init
      - run: terraform state pull > state-backup.json
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: state-backup
          path: state-backup.json
      - run: terraform state rm "${{ inputs.address }}"
